sources:
  #- url: https://stock.hostmonit.com/CloudFlareYesV6
  #- url: https://ipdb.030101.xyz/bestcfv6
  #- url: https://www.wetest.vip/page/cloudflare/address_v6.html
  #- url: https://www.wetest.vip/page/cloudfront/total_v6.html
  #- url: https://addressesapi.090227.xyz/cmcc-ipv6

  - url: https://stock.hostmonit.com/CloudFlareYesV6
    page_type: dynamic
    selector: "td.el-table_2_column_14 div.cell"
    wait_time: 8000

  - url: https://ipdb.030101.xyz/bestcfv6
    page_type: dynamic
    wait_time: 10000

  - url: https://www.wetest.vip/page/cloudflare/address_v6.html
    page_type: static
    selector: "td[data-label='优选地址']" 

  - url: https://www.wetest.vip/page/cloudfront/total_v6.html
    page_type: static
    selector: "td[data-label='优选地址']" 

  - url: https://addressesapi.090227.xyz/cmcc-ipv6
    page_type: api



pattern: '[0-9a-fA-F]{1,4}:[0-9a-fA-F:]+'
output: "ipv6.txt"
timeout: 10
log: "fetch_cloudflare_ipv6.log"
max_workers: 4
log_level: "INFO"
js_retry: 3
timeout: 30
js_retry_interval: 2.0
max_ips_per_url: 20
per_url_limit_mode: "top"
exclude_ips:
  - "2001:db8::1"
  - "2001:db8::/64"
allowed_regions:        # 只保留这些地区的IP，使用国家/地区代码（如CN、US、HK、JP等），留空或缺省则不过滤
 # - "US"
 # - "HK"
ip_geo_api: "http://ip-api.com/json/{ip}"
auto_detect: true
xpath_support: true
follow_redirects: true
enable_telegram_notification: True
