sources:
  - url: https://stock.hostmonit.com/CloudFlareYesV6
  - url: https://ipdb.030101.xyz/bestcfv6
  - url: https://www.wetest.vip/page/cloudflare/address_v6.html
  - url: https://www.wetest.vip/page/cloudfront/total_v6.html
pattern: '[0-9a-fA-F]{1,4}:[0-9a-fA-F:]+'
output: "ipv6.txt"
timeout: 10
log: "fetch_cloudflare_ipv6.log"
max_workers: 4
log_level: "INFO"
js_retry: 3
js_retry_interval: 2.0
max_ips_per_url: 10
per_url_limit_mode: "top"
exclude_ips:
  - "2001:db8::1"
  - "2001:db8::/64"
allowed_regions:
  - "US"
  - "HK"
ip_geo_api: "http://ip-api.com/json/{ip}"
auto_detect: true
xpath_support: true
follow_redirects: true
enable_telegram_notification: True
