name: Update Cloudflare IP List

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
  watch:
    types: started

    
jobs:
  update-ip-list:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整历史记录
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python -m playwright install
    
    - name: Run IP fetcher
      run: python fetch_cloudflare_ips.py
        
    - name: Commit and push changes
      if: success()
      run: |
        # 检查ip.txt是否有变化
        if git diff --quiet ip.txt; then
          echo "No changes detected in ip.txt, skipping commit."
        else
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add ip.txt
          git commit -m "Auto update Cloudflare IPs"
          git push
        fi
    - name: Run IP fetch script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python fetch_cloudflare_ips.py
